# package.json в такой сборке содержит последнюю версию, однако он не соотвветствует папке node_modules.
# папка node_modules берется готовой из образа kopnik-modules

FROM node:latest
WORKDIR /app
COPY ./ ./
#RUN ls -la
