version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    container_name: app
    restart: always
#    volumes:
#      - .:/app
    ports:
      - ${APP_PORT}:3000
    environment:
      - DB_SID=ORCLCDB.localdomain

    command: [ "npm", "start" ]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    volumes:
      - ../kopnik-db/db-${NODE_ENV}:/var/lib/postgresql/data
      - ../kopnik-db/dumps-${NODE_ENV}:/var/lib/postgresql/dumps
    ports:
      - ${DB_PORT}:5432
#        networks:
#            - backend


