version: '3.7'
services:
  node:
    image: kopnikorg/kopnik-node:latest
    environment:
      # переопределяем параметры подключения для работы сервера в контейнере
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./.env:/app/.env
    ports:
      # внутри тоже порты разные, чтобы можно было и без контейнера одновременно  запустить сервера дев и тест
      - ${APP_PORT}:${APP_PORT}
    command: [ "npm", "start" ]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    volumes:
      - ../kopnik-db/db-${NODE_ENV}:/var/lib/postgresql/data
      - ../kopnik-db/dumps-${NODE_ENV}:/var/lib/postgresql/dumps
    ports:
      - ${DB_PORT}:5432

  client:
    image: kopnikorg/kopnik-client:latest
    volumes:
      - dist:/app/dist
    command: [ "sleep", "1000000" ]

  nginx:
    image: nginx:latest
    volumes:
      - /home/someuser/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/someuser/nginx/templates:/etc/nginx/templates
      - /home/someuser/certs:/etc/nginx/certs/
      - dist:/app/dist
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=staging.kopnik.org
    network_mode: host
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - /home/someuser/certs:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  dist:
