version: '3.7'
services:
  app:
    image: node
    container_name: app
    restart: always
#    volumes:
#      - .:/user/dashboard
    ports:
      - ${APP_PORT}:3000
    environment:
      - DB_SID=ORCLCDB.localdomain
    command: ["npm", "start"]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    volumes:
      - ./var/db:/var/lib/postgresql/data
      - ./var/db_dumps/postgresql:/var/lib/postgresql/dumps
    ports:
      - ${DB_PORT}:5432
#        networks:
#            - backend
