http.host: 0.0.0.0
xpack.monitoring.elasticsearch.hosts: ["elasticsearch:9200"]
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: "${LOGSTASH_USER}"
xpack.monitoring.elasticsearch.password: "${LOGSTASH_PWD}"
