name: "test"
env:
  DB_USER: db_user
  DB_PASSWORD: db_password
  DB_DB: db_name
  DB_PORT: 5432
  DB_HOST: localhost
  NODE_ENV: test
on:
  push:
    branches:
      - main
      - fix*
      - feature*

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.0.1
          registry-url: https://registry.npmjs.org

      # prepare .env file
      - run: cp default.env .env
      - run: sed -i 's/VK_CLIENT_SECRET=/VK_CLIENT_SECRET=${{ secrets.VK_CLIENT_SECRET }}/g' .env
      - run: sed -i 's/VK_SVETOSLAV_TOKEN=/VK_SVETOSLAV_TOKEN=${{ secrets.VK_SVETOSLAV_TOKEN }}/g' .env

      - run: docker-compose up -d db
      - run: npm i
      - run: npm run typeorm:migration:run
      - run: npm test

  build:
    name: build
    if: github.ref == 'refs/heads/mainr'
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker build --no-cache -t kopnikorg/kopnik-node:latest ./.docker/app/
      - run: docker login -u alexey2baranov -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push kopnikorg/kopnik-node:latest

  deploy:
    name: deploy
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        uses: alexey2baranov/github-action-ssh@release
        with:
          command: |
            cd ${{ secrets.SSH_PATH }}
            cp default.env .env
            sed -i 's/VK_CLIENT_SECRET=/VK_CLIENT_SECRET=${{ secrets.VK_CLIENT_SECRET }}/g' .env
            sed -i 's/VK_SVETOSLAV_TOKEN=/VK_SVETOSLAV_TOKEN=${{ secrets.VK_SVETOSLAV_TOKEN }}/g' .env
            git pull
            docker-compose down
            docker-compose pull --quiet
            docker-compose up -d
          host: ${{ secrets.SSH_HOST }}
          username: someuser
          password: ${{ secrets.SSH_PASSWORD }}
